"""
VIGIL-AI: Central Calls REST & WebSocket API.
Implements universal incoming-call triggers, real-time status retrieval,
in-flight analysis posting, risk updating, automatic termination, and dashboard WebSockets.
"""
import uuid
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List
from fastapi import APIRouter, Depends, HTTPException, WebSocket, WebSocketDisconnect, status, Query
from pydantic import BaseModel, Field

from app.core.logging import logger
from app.core.security import verify_api_key, anonymize_caller_id
from app.services.caller_service import CallerService
from app.services.call_history_service import CallHistoryService
from app.services.risk_service import RiskService
from app.services.call_record_service import CallRecordService
from app.services.dashboard_event_bus import dashboard_event_bus
from app.db.connection import get_db_pool

router = APIRouter()

# Service singletons
caller_service = CallerService()
call_history_service = CallHistoryService()
risk_service = RiskService()
call_record_service = CallRecordService()

# ────────────────────────────────────────────────────────────
# Request & Response Schemas
# ────────────────────────────────────────────────────────────

class IncomingCallRequest(BaseModel):
    call_id: Optional[str] = Field(None, description="Unique call identifier if generated by client")
    phone_number: str = Field(..., description="Raw caller phone number")
    caller_name: Optional[str] = Field(None, description="Caller display name from device contact book")
    company_name: Optional[str] = Field(None, description="Claimed corporate affiliation")
    contact_match: Optional[bool] = Field(False, description="Whether number matched device address book")
    contact_known: Optional[bool] = Field(None, description="Whether caller is known contact")
    caller_type: Optional[str] = Field(None, description="Caller category")
    stir_shaken_status: Optional[int] = Field(0, description="0=Unverified, 1=Passed, 2=Failed")
    carrier_code: Optional[str] = Field(None, description="Network carrier code")
    device_id: Optional[str] = Field("android_device_primary", description="Reporting mobile device ID")
    user_id: Optional[str] = Field(None, description="VIGIL-AI account user ID")
    call_direction: str = Field("INCOMING", description="Call direction")
    claimed_relationship: Optional[str] = Field(None, description="e.g. FRIEND, FAMILY, BANK")
    call_transport: str = Field("CELLULAR", description="CELLULAR or VOIP")

class IncomingCallResponse(BaseModel):
    call_id: str
    phone_number: str
    normalized_phone_number: str
    masked_phone: str
    caller_name: str
    company: Optional[str]
    company_verification_status: str
    contact_known: bool
    caller_type: str
    previous_calls: int
    calls_today: int
    last_call_timestamp: Optional[str]
    initial_risk: int
    risk_level: str
    recommended_action: str
    status: str = "RINGING"
    call_status: str = "RINGING"
    speaker_verification_status: str  # WAITING | ANALYZING | VERIFIED | MISMATCH
    deepfake_detection_status: str     # WAITING | ANALYZING | CLEAN | SYNTHETIC
    liveness_status: str               # WAITING | ANALYZING | LIVE | REPLAY
    cellular_audio_available: bool     # False for standard Android cellular
    timestamp: str

class CallAnalysisRequest(BaseModel):
    window_start_ms: int = 0
    window_end_ms: int = 2000
    deepfake_probability: float
    bonafide_probability: Optional[float] = None
    speaker_similarity: Optional[float] = None
    liveness_score: Optional[float] = None
    replay_probability: Optional[float] = None
    confidence: float = 0.95
    uncertainty: Optional[float] = 0.0
    voice_activity: Optional[str] = None
    signal_quality: Optional[str] = "GOOD"
    vad_speech_detected: bool = True
    transcript_segment: Optional[str] = None

class CallRiskUpdateRequest(BaseModel):
    risk_score: int
    risk_level: str
    signals: List[str] = []
    contributing_signals: List[str] = []
    action: str = "MONITOR"
    reason: str = "Risk update"
    confidence: float = 0.95

class CallActionRequest(BaseModel):
    action: str = Field(..., description="ALLOW | MONITOR | CHALLENGE | WARN | SILENCE | BLOCK | TERMINATE")
    reason: str = Field(..., description="Human or algorithmic justification")
    risk_score: Optional[int] = None
    triggered_by: str = Field("policy_engine", description="risk_engine | soc_operator | policy_engine")

class TerminateCallRequest(BaseModel):
    reason: str = Field("Critical fraud threat detected: automatic call termination enforced", description="Termination rationale")
    risk_score: Optional[int] = 100
    deepfake_probability: Optional[float] = None
    speaker_similarity: Optional[float] = None
    signals: Optional[List[str]] = None

# ────────────────────────────────────────────────────────────
# 1. Universal Incoming-Call Trigger
# ────────────────────────────────────────────────────────────

@router.post("/incoming", response_model=IncomingCallResponse, status_code=status.HTTP_200_OK)
async def handle_incoming_call(payload: IncomingCallRequest):
    """
    CRITICAL BEHAVIOR: UNIVERSAL INCOMING-CALL TRIGGER.
    VIGIL-AI activates for EVERY incoming call (unknown, known, saved contact, family, business).
    A known phone number is NEVER considered proof of legitimate speaker (SIM spoofing/hijack).
    Phone-number identity and voice identity are strictly separated.
    Captures metadata immediately, writes record to Supabase, and broadcasts 'incoming_call' to dashboard WebSocket.
    """
    call_id = payload.call_id or str(uuid.uuid4())
    raw_number = payload.phone_number
    normalized = caller_service.normalize_phone_number(raw_number)
    masked_phone = anonymize_caller_id(raw_number)
    now_iso = datetime.now(timezone.utc).isoformat()

    logger.info(f"🚨 UNIVERSAL INCOMING-CALL TRIGGER for {masked_phone} (call_id: {call_id}, contact_match: {payload.contact_match})")

    # Retrieve caller profile and history (isolated by user_id)
    caller = await caller_service.get_caller_by_number(
        phone_number=normalized,
        user_id=payload.user_id,
        display_name_hint=payload.caller_name,
        claimed_company=payload.company_name,
        claimed_relationship=payload.claimed_relationship
    )
    history = await call_history_service.get_history_summary(normalized, caller.id, user_id=payload.user_id)

    # Preliminary risk evaluation
    risk_assessment, recommended_action = risk_service.evaluate_preliminary_risk(
        caller=caller,
        history=history,
        stir_shaken_status=payload.stir_shaken_status or 0
    )

    contact_is_known = bool(
        payload.contact_match or 
        payload.contact_known or
        (payload.caller_type and payload.caller_type.lower() in ["contact", "saved_contact"]) or
        (caller.trust_status in ["contact", "trusted"]) or 
        (caller.caller_type and caller.caller_type.lower() in ["contact", "saved_contact"])
    )
    caller_display = payload.caller_name or caller.name or ("Known Contact" if contact_is_known else "Unknown Caller")

    # Platform capabilities delineation
    is_cellular = (payload.call_transport.upper() == "CELLULAR")
    cellular_audio_avail = False  # Explicit truth: cellular in-call audio not accessible on standard Android

    call_session_data = {
        "call_id": call_id,
        "session_id": call_id,
        "phone_number": raw_number,
        "normalized_phone_number": normalized,
        "masked_phone": masked_phone,
        "caller_name": caller_display,
        "company": caller.company or caller.company_name_claimed,
        "company_verification_status": caller.verification_status,
        "contact_known": contact_is_known,
        "caller_type": caller.caller_type,
        "previous_calls": history.total_calls,
        "calls_today": history.calls_last_24h,
        "last_call_timestamp": getattr(history, "last_call_timestamp", None) or now_iso,
        "initial_risk": risk_assessment.score,
        "risk_level": risk_assessment.level,
        "recommended_action": recommended_action,
        "current_action": recommended_action,
        "speaker_verification_status": "WAITING",
        "deepfake_detection_status": "WAITING",
        "liveness_status": "WAITING",
        "voice_activity": "NO_AUDIO_YET",
        "cellular_audio_available": cellular_audio_avail,
        "call_transport": payload.call_transport.upper(),
        "call_status": "RINGING",
        "status": "RINGING",
        "timestamp": now_iso,
        "threat_signals": risk_assessment.reasons,
        "audio_stream_active": False,
        "user_id": payload.user_id,
        "device_id": payload.device_id,
    }

    # Store in memory event bus
    dashboard_event_bus.set_active_call(call_id, call_session_data)

    # Persist call session to Supabase public.calls & public.call_actions immediately
    try:
        await call_record_service.record_screening_call(
            session_id=call_id,
            phone_number=raw_number,
            normalized_number=normalized,
            caller_id=caller.id,
            caller_name=caller_display,
            company_name=caller.company,
            company_verified=caller.company_verified,
            company_name_claimed=caller.company_name_claimed,
            company_name_verified=caller.company_name_verified,
            verification_source=caller.verification_source,
            verification_status=caller.verification_status,
            relationship=caller.relationship,
            relationship_verified=caller.relationship_verified,
            caller_type=caller.caller_type,
            previous_calls_count=history.total_calls,
            calls_last_1h=history.calls_last_1h,
            calls_last_24h=history.calls_last_24h,
            calls_last_7d=history.calls_last_7d,
            average_call_duration=history.average_call_duration_sec,
            failed_verifications=history.failed_verifications,
            suspicious_calls=history.suspicious_events,
            blocked_calls=history.blocked_calls,
            risk_score=risk_assessment.score,
            risk_level=risk_assessment.level,
            action_taken=recommended_action,
            action_reason="; ".join(risk_assessment.reasons),
            model_version="v1.0-vigil-telephony",
            user_id=payload.user_id
        )
    except Exception as e:
        logger.warning(f"Could not persist call record to Supabase: {e}")

    # BROADCAST TO LAPTOP DASHBOARD IMMEDIATELY VIA WEBSOCKET (with user_id isolation)
    await dashboard_event_bus.broadcast_event(
        event_type="incoming_call",
        payload={
            "call_id": call_id,
            "phone_number": raw_number,
            "normalized_phone_number": normalized,
            "masked_phone": masked_phone,
            "caller_name": caller_display,
            "company": caller.company or caller.company_name_claimed,
            "company_verification_status": caller.verification_status,
            "contact_known": contact_is_known,
            "caller_type": caller.caller_type,
            "previous_calls": history.total_calls,
            "calls_today": history.calls_last_24h,
            "last_call_timestamp": history.last_call_timestamp or now_iso,
            "initial_risk": risk_assessment.score,
            "risk_level": risk_assessment.level,
            "recommended_action": recommended_action,
            "speaker_verification_status": "WAITING",
            "deepfake_detection_status": "WAITING",
            "liveness_status": "WAITING",
            "cellular_audio_available": cellular_audio_avail,
            "call_transport": payload.call_transport.upper(),
            "timestamp": now_iso,
            "threat_signals": risk_assessment.reasons,
        },
        call_id=call_id,
    )

    try:
        from app.api.v1.endpoints.screening import record_live_screened_call
        record_live_screened_call({
            "timestamp": now_iso,
            "phone_number": raw_number,
            "normalized_number": normalized,
            "masked_phone": masked_phone,
            "caller_name": caller_display,
            "company_name": caller.company or caller.company_name_claimed,
            "company_badge": None,
            "verification_status": caller.verification_status,
            "trust_status": caller.trust_status,
            "risk_score": risk_assessment.score,
            "risk_level": risk_assessment.level,
            "action": recommended_action,
            "reasons": risk_assessment.reasons,
            "voice_deepfake_pct": 0,
            "voice_identity_pct": 0,
            "voice_liveness_pct": 0,
            "warning_banner": None,
            "calls_summary_total": history.total_calls,
            "calls_summary_today": history.calls_last_24h,
            "call_id": call_id,
            "user_id": payload.user_id,
            "target_phone": payload.user_id or "Registered Device",
            "subscriber_phone": payload.user_id or "Registered Device",
        })
    except Exception as e:
        logger.debug(f"Could not record live screened call: {e}")

    return IncomingCallResponse(**call_session_data)

# ────────────────────────────────────────────────────────────
# 2. Call Details Retrieval
# ────────────────────────────────────────────────────────────

@router.get("/{call_id}")
async def get_call_details(call_id: str):
    """Retrieves current live state and analysis metrics for a call session."""
    active = dashboard_event_bus.get_active_call(call_id)
    if active:
        return {**active, "status": active.get("status", active.get("call_status", "ACTIVE"))}

    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                row = await conn.fetchrow("SELECT * FROM public.calls WHERE session_id = $1 OR id::text = $1", call_id)
                if row:
                    return dict(row)
        except Exception as e:
            logger.warning(f"Error reading call {call_id} from DB: {e}")

    raise HTTPException(status_code=404, detail=f"Call session {call_id} not found")

# ────────────────────────────────────────────────────────────
# 3. Post In-Call Analysis Window
# ────────────────────────────────────────────────────────────

@router.post("/{call_id}/analysis")
async def post_call_analysis(call_id: str, analysis: CallAnalysisRequest):
    """Receives an audio analysis window result, updates state, and broadcasts to dashboard."""
    active = dashboard_event_bus.get_active_call(call_id)
    if not active:
        logger.debug(f"Analysis posted for inactive call cache {call_id}. Initializing entry.")
        active = {"call_id": call_id, "session_id": call_id}
        dashboard_event_bus.set_active_call(call_id, active)

    bonafide = analysis.bonafide_probability if analysis.bonafide_probability is not None else (1.0 - analysis.deepfake_probability)
    replay = analysis.replay_probability if analysis.replay_probability is not None else (1.0 - (analysis.liveness_score or 1.0))

    active.update({
        "deepfake_probability": round(analysis.deepfake_probability, 3),
        "speaker_similarity": round(analysis.speaker_similarity, 3) if analysis.speaker_similarity is not None else None,
        "liveness_score": round(analysis.liveness_score, 3) if analysis.liveness_score is not None else None,
        "replay_probability": round(replay, 3),
        "voice_activity": "YES" if analysis.vad_speech_detected else "NO",
        "audio_detected": True,
        "signal_quality": "GOOD",
        "speaker_verification_status": "VERIFIED" if (analysis.speaker_similarity or 0) >= 0.85 else ("MISMATCH" if analysis.speaker_similarity is not None else "ANALYZING"),
        "deepfake_detection_status": "SYNTHETIC" if analysis.deepfake_probability >= 0.70 else "CLEAN",
        "liveness_status": "LIVE" if (analysis.liveness_score or 1.0) >= 0.50 else "REPLAY",
    })

    if analysis.transcript_segment:
        active["live_transcript"] = analysis.transcript_segment

    # Multi-signal rolling composite risk evaluation
    df_pct = analysis.deepfake_probability * 100.0
    spk_sim = analysis.speaker_similarity
    live_score = analysis.liveness_score if analysis.liveness_score is not None else 1.0
    uncertainty = analysis.uncertainty or 0.0

    calculated_risk = 15
    signals = []

    # 1. Acoustic synthetic threat (WavLM-AASIST)
    if df_pct >= 85 and uncertainty < 0.4:
        calculated_risk = max(calculated_risk, 95)
        signals.append("High confidence synthetic voice detected (WavLM-AASIST)")
    elif df_pct >= 60 and uncertainty < 0.5:
        calculated_risk = max(calculated_risk, 75)
        signals.append("Possible voice clone / vocoder anomaly")
    elif df_pct >= 40:
        calculated_risk = max(calculated_risk, 45)
        signals.append("Elevated synthetic speech indicators")

    # 2. Speaker verification (ECAPA-TDNN)
    if spk_sim is not None:
        if spk_sim < 0.40 and uncertainty < 0.5:
            calculated_risk = max(calculated_risk, 65)
            signals.append("Speaker mismatch with claimed enrolled identity")
        elif spk_sim >= 0.85:
            if df_pct >= 60:
                # Targeted voice clone: matches voiceprint BUT exhibits synthetic vocoder artifacts
                calculated_risk = max(calculated_risk, 95)
                signals.append("Targeted AI voice clone detected (biometric mimicry + synthetic artifacts)")
            else:
                calculated_risk = max(10, min(calculated_risk, 25))
                signals.append("Speaker biometric verified (ECAPA-TDNN)")

    # 3. Liveness check
    if live_score < 0.40 and uncertainty < 0.5:
        calculated_risk = max(calculated_risk, 60)
        signals.append("Low acoustic liveness (replay attack risk)")

    # 4. Uncertainty penalty/moderation
    if uncertainty >= 0.6:
        # Heavily uncertain audio: do not falsely terminate
        calculated_risk = min(calculated_risk, 45)
        signals.append("High acoustic uncertainty (heavy background noise)")

    if calculated_risk >= 85:
        risk_level = "CRITICAL"
        action = "TERMINATE"
    elif calculated_risk >= 60:
        risk_level = "HIGH"
        action = "WARN"
    elif calculated_risk >= 35:
        risk_level = "MEDIUM"
        action = "CHALLENGE"
    else:
        risk_level = "LOW"
        action = "ALLOW"

    active["risk_score"] = calculated_risk
    active["risk_level"] = risk_level
    active["action"] = action
    active["threat_signals"] = signals

    user_id = active.get("user_id") if active else None

    # Broadcast event (with user_id isolation)
    await dashboard_event_bus.broadcast_event(
        event_type="analysis_update",
        payload={
            "deepfake_probability": round(analysis.deepfake_probability, 3),
            "speaker_similarity": round(analysis.speaker_similarity, 3) if analysis.speaker_similarity is not None else None,
            "liveness_score": round(analysis.liveness_score, 3) if analysis.liveness_score is not None else None,
            "replay_probability": round(replay, 3),
            "voice_activity": "YES" if analysis.vad_speech_detected else "NO",
            "confidence": analysis.confidence,
            "risk_score": calculated_risk,
            "risk_level": risk_level,
            "action": action,
            "signals": signals,
            "transcript_segment": analysis.transcript_segment,
        },
        call_id=call_id,
        user_id=user_id
    )

    if action == "TERMINATE":
        active["call_status"] = "TERMINATED"
        await dashboard_event_bus.broadcast_event(
            event_type="call_terminated",
            payload={
                "reason": "Automated Multi-Signal Confirmation: High-confidence synthetic voice attack detected.",
                "risk_score": calculated_risk,
                "signals": signals,
            },
            call_id=call_id,
            user_id=user_id
        )

    # Persist to public.voice_analysis asynchronously
    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                # Find DB UUID of call
                call_row = await conn.fetchrow("SELECT id FROM public.calls WHERE session_id = $1 LIMIT 1", call_id)
                if call_row:
                    await conn.execute("""
                        INSERT INTO public.voice_analysis (
                            call_id, window_start_ms, window_end_ms, deepfake_probability,
                            bonafide_probability, speaker_similarity, liveness_score, replay_probability,
                            confidence, vad_speech_confidence, model_version
                        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'WavLM-AASIST-ECAPA')
                    """, call_row["id"], analysis.window_start_ms, analysis.window_end_ms,
                       analysis.deepfake_probability, bonafide, analysis.speaker_similarity,
                       analysis.liveness_score, replay, analysis.confidence, 1.0 if analysis.vad_speech_detected else 0.0)
        except Exception as e:
            logger.debug(f"Failed to persist voice_analysis row: {e}")

    return {
        "status": "success",
        "call_id": call_id,
        "risk_score": calculated_risk,
        "risk_level": risk_level,
        "action": action,
        "signals": signals,
    }

# ────────────────────────────────────────────────────────────
# 4. Post Risk Update
# ────────────────────────────────────────────────────────────

@router.post("/{call_id}/risk")
async def post_call_risk(call_id: str, risk: CallRiskUpdateRequest):
    """Updates composite risk score and broadcasts 'risk_update' to dashboard."""
    active = dashboard_event_bus.get_active_call(call_id)
    if active:
        active.update({
            "risk_score": risk.risk_score,
            "risk_level": risk.risk_level,
            "current_action": risk.action,
            "action": risk.action,
            "threat_signals": risk.signals,
            "contributing_signals": risk.contributing_signals,
        })

    user_id = active.get("user_id") if active else None

    await dashboard_event_bus.broadcast_event(
        event_type="risk_update",
        payload={
            "risk_score": risk.risk_score,
            "risk_level": risk.risk_level,
            "action": risk.action,
            "signals": risk.signals,
            "contributing_signals": risk.contributing_signals,
            "reason": risk.reason,
            "confidence": risk.confidence,
        },
        call_id=call_id,
        user_id=user_id
    )

    # Persist risk event to public.risk_events
    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                call_row = await conn.fetchrow("SELECT id FROM public.calls WHERE session_id = $1 LIMIT 1", call_id)
                if call_row:
                    import json
                    await conn.execute("""
                        INSERT INTO public.risk_events (
                            call_id, event_type, risk_score, risk_level, reason, confidence, contributing_signals
                        ) VALUES ($1, 'multi_signal_risk', $2, $3, $4, $5, $6::jsonb)
                    """, call_row["id"], risk.risk_score, risk.risk_level, risk.reason, risk.confidence, json.dumps(risk.contributing_signals))
                    await conn.execute("""
                        UPDATE public.calls SET overall_risk_score = $2, overall_risk_level = $3 WHERE id = $1
                    """, call_row["id"], risk.risk_score, risk.risk_level)
        except Exception as e:
            logger.debug(f"Failed to record risk_event: {e}")

    return {"status": "success", "call_id": call_id, "risk_score": risk.risk_score}

# ────────────────────────────────────────────────────────────
# 5. Policy Enforcement Action
# ────────────────────────────────────────────────────────────

@router.post("/{call_id}/action")
async def execute_call_action(call_id: str, act: CallActionRequest):
    """Executes a policy action (ALLOW, MONITOR, CHALLENGE, WARN, SILENCE, BLOCK, TERMINATE)."""
    action_upper = act.action.upper()
    now_iso = datetime.now(timezone.utc).isoformat()

    active = dashboard_event_bus.get_active_call(call_id)
    if active:
        active["current_action"] = action_upper
        active["action"] = action_upper
        active["call_status"] = "BLOCKED" if action_upper in ["BLOCK", "TERMINATE"] else ("WARNED" if action_upper == "WARN" else "MONITORING")

    event_name = "call_terminated" if action_upper == "TERMINATE" else ("call_blocked" if action_upper == "BLOCK" else "warning_issued")
    user_id = active.get("user_id") if active else None

    await dashboard_event_bus.broadcast_event(
        event_type=event_name,
        payload={
            "action": action_upper,
            "reason": act.reason,
            "risk_score": act.risk_score or 100,
            "triggered_by": act.triggered_by,
        },
        call_id=call_id,
        user_id=user_id
    )

    # Persist action to public.call_actions
    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                call_row = await conn.fetchrow("SELECT id FROM public.calls WHERE session_id = $1 LIMIT 1", call_id)
                if call_row:
                    await conn.execute("""
                        INSERT INTO public.call_actions (
                            call_id, action, reason, risk_score, triggered_by
                        ) VALUES ($1, $2, $3, $4, $5)
                    """, call_row["id"], action_upper, act.reason, act.risk_score or 100, act.triggered_by)
                    await conn.execute("""
                        UPDATE public.calls SET final_action = $2, call_status = $3 WHERE id = $1
                    """, call_row["id"], action_upper, "blocked" if action_upper in ["BLOCK", "TERMINATE"] else "in_progress")
        except Exception as e:
            logger.warning(f"Error persisting call action: {e}")

    return {"status": "enforced", "call_id": call_id, "action": action_upper}

# ────────────────────────────────────────────────────────────
# 6. Automatic Call Termination Endpoint
# ────────────────────────────────────────────────────────────

@router.post("/{call_id}/terminate")
async def terminate_call(call_id: str, payload: TerminateCallRequest):
    """
    IMMEDIATE ENFORCEMENT ACTION: AUTOMATIC CALL TERMINATION.
    Executed when risk engine reaches CRITICAL threat with high confidence.
    Immediately signals call termination to audio stream, cuts session, logs audit, and updates dashboard.
    """
    logger.warning(f"🛑 ENFORCING AUTOMATIC CALL TERMINATION for session {call_id}: {payload.reason}")
    now = datetime.now(timezone.utc)

    active = dashboard_event_bus.get_active_call(call_id)
    if active:
        active["call_status"] = "TERMINATED"
        active["status"] = "TERMINATED"
        active["current_action"] = "TERMINATE"
        active["action"] = "TERMINATE"
        active["risk_score"] = payload.risk_score or 100
        active["risk_level"] = "CRITICAL"
        active["termination_reason"] = payload.reason
        active["ended_at"] = now.isoformat()

    # 1. Broadcast call_terminated event across WebSocket
    await dashboard_event_bus.broadcast_event(
        event_type="call_terminated",
        payload={
            "action": "TERMINATE",
            "risk_score": payload.risk_score or 100,
            "risk_level": "CRITICAL",
            "reason": payload.reason,
            "deepfake_probability": payload.deepfake_probability or (active.get("deepfake_probability") if active else 0.94),
            "speaker_similarity": payload.speaker_similarity or (active.get("speaker_similarity") if active else 0.28),
            "timestamp": now.isoformat(),
        },
        call_id=call_id
    )

    # 2. Persist audit record to Supabase PostgreSQL
    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                call_row = await conn.fetchrow("SELECT id FROM public.calls WHERE session_id = $1 LIMIT 1", call_id)
                if call_row:
                    c_id = call_row["id"]
                    # Add to call_actions
                    await conn.execute("""
                        INSERT INTO public.call_actions (
                            call_id, action, reason, risk_score, triggered_by, performed_at
                        ) VALUES ($1, 'TERMINATE', $2, $3, 'risk_engine_enforcement', $4)
                    """, c_id, payload.reason, payload.risk_score or 100, now)

                    # Update call record
                    await conn.execute("""
                        UPDATE public.calls
                        SET call_status = 'blocked',
                            final_action = 'BLOCK',
                            action_reason = $2,
                            overall_risk_score = $3,
                            overall_risk_level = 'CRITICAL',
                            ended_at = $4
                        WHERE id = $1
                    """, c_id, payload.reason, payload.risk_score or 100, now)
        except Exception as e:
            logger.warning(f"Error persisting call termination audit: {e}")

    return {
        "status": "TERMINATED",
        "call_id": call_id,
        "action": "TERMINATE",
        "reason": payload.reason,
        "enforced_at": now.isoformat()
    }

# ────────────────────────────────────────────────────────────
# 7. Caller Intelligence Lookup Endpoints
# ────────────────────────────────────────────────────────────

@router.get("/callers/lookup/{phone_number}")
async def lookup_caller_profile(phone_number: str):
    """Returns caller intelligence profile by phone number."""
    normalized = caller_service.normalize_phone_number(phone_number)
    caller = await caller_service.get_caller_by_number(normalized)
    history = await call_history_service.get_history_summary(normalized, caller.id)
    risk_assessment, recommended_action = risk_service.evaluate_preliminary_risk(caller, history)
    sec_profile = risk_service.calculate_security_profile(caller, history, risk_assessment)

    return {
        "caller": caller,
        "history": history,
        "risk": risk_assessment,
        "recommended_action": recommended_action,
        "security_profile": sec_profile,
    }

@router.get("/callers/{caller_id}")
async def get_caller_by_id(caller_id: str):
    """Retrieves caller record by UUID."""
    pool = await get_db_pool()
    if pool:
        try:
            async with pool.acquire() as conn:
                row = await conn.fetchrow("""
                    SELECT c.*, p.normalized_number, comp.name AS company_name, comp.verified AS company_verified
                    FROM public.callers c
                    LEFT JOIN public.phone_numbers p ON p.caller_id = c.id
                    LEFT JOIN public.companies comp ON comp.id = c.company_id
                    WHERE c.id::text = $1 AND c.deleted_at IS NULL
                    LIMIT 1
                """, caller_id)
                if row:
                    return dict(row)
        except Exception as e:
            logger.warning(f"Error fetching caller {caller_id}: {e}")

    raise HTTPException(status_code=404, detail="Caller not found")

# ────────────────────────────────────────────────────────────
# 8. WebSockets for Laptop Dashboard
# ────────────────────────────────────────────────────────────

ws_router = APIRouter()

@ws_router.websocket("/ws/dashboard")
@router.websocket("/ws/dashboard")
async def websocket_dashboard_feed(websocket: WebSocket, user_id: Optional[str] = Query(None)):
    """
    Real-Time Laptop SOC Dashboard WebSocket Feed with per-user tenant isolation.
    Zero-polling live event pipeline: receives incoming_call, risk_update,
    live telemetry, and automatic termination events for the active user account.
    """
    await websocket.accept()
    await dashboard_event_bus.register_dashboard_client(websocket, user_id=user_id)

    # Send initial snapshot of active calls for this specific user
    try:
        active_calls = dashboard_event_bus.get_all_active_calls(user_id=user_id)
        await websocket.send_json({
            "event": "system_status",
            "user_id": user_id,
            "backend": "ONLINE",
            "database": "ONLINE",
            "ai_service": "ONLINE",
            "websocket": "CONNECTED",
            "cellular_monitoring": "PRE_CALL_SCREENING_ONLY",
            "voip_monitoring": "REAL_TIME_AUDIO_AND_AUTO_TERMINATE",
            "active_calls_count": len(active_calls),
            "active_calls": active_calls,
            "timestamp": datetime.now(timezone.utc).isoformat()
        })
    except Exception as e:
        logger.debug(f"Error sending dashboard handshake: {e}")

    try:
        while True:
            data = await websocket.receive_text()
            try:
                import json
                msg = json.loads(data)
                if str(msg.get("type", "")).upper() == "PING":
                    await websocket.send_json({"type": "pong", "timestamp": msg.get("timestamp")})
            except Exception:
                pass
    except (WebSocketDisconnect, RuntimeError):
        pass
    finally:
        await dashboard_event_bus.unregister_dashboard_client(websocket, user_id=user_id)

@ws_router.websocket("/ws/calls/{call_id}")
@router.websocket("/ws/calls/{call_id}")
async def websocket_call_feed(websocket: WebSocket, call_id: str):
    """Dedicated WebSocket channel for a single call session."""
    await websocket.accept()
    await dashboard_event_bus.register_call_client(call_id, websocket)

    active = dashboard_event_bus.get_active_call(call_id)
    if active:
        try:
            await websocket.send_json({"event": "call_state", **active})
        except Exception:
            pass

    try:
        while True:
            await websocket.receive_text()
    except (WebSocketDisconnect, RuntimeError):
        pass
    finally:
        await dashboard_event_bus.unregister_call_client(call_id, websocket)
